function s2() {
    var ra = document.querySelector('.inp1')
    var ram = ra.value - 1
    fetch("https://jsonplaceholder.typicode.com/users")
        .then(response => response.json())
        .then(resp => document.querySelector('.text').innerHTML = resp[ram].name)
    fetch("https://jsonplaceholder.typicode.com/users")
        .then(response => response.json())
        .then(resp => document.querySelector('.l').innerHTML = resp[ram].id)
    fetch("https://jsonplaceholder.typicode.com/photos")
        .then(response => response.json())
        .then(resp => document.querySelector('.img').src = resp[Math.ceil(Math.random() * 5005)].url)
    fetch("https://jsonplaceholder.typicode.com/users")
        .then(response => response.json())
        .then(resp => document.querySelector('.p').innerHTML = resp[ram].address.suite[5] + resp[ram].address.suite[6] + resp[ram].address.suite[7])
    fetch("https://jsonplaceholder.typicode.com/posts")
        .then(response => response.json())
        .then(resp => document.querySelector('.te').innerHTML = resp[Math.ceil(Math.random() * 100)].body)
    fetch("https://jsonplaceholder.typicode.com/users")
        .then(response => response.json())
        .then(resp => document.querySelector('.data').href = resp[ram].website)
    fetch("https://jsonplaceholder.typicode.com/users")
        .then(response => response.json())
        .then(resp => document.querySelector('.data').innerHTML = resp[ram].website)
}

function s() {
    const ra2 = document.querySelector('.inp2')
    var ram2 = ra2.value - 1
    fetch("https://jsonplaceholder.typicode.com/users")
        .then(response => response.json())
        .then(resp => document.querySelector('.text2').innerHTML = resp[ram2].name)
    fetch("https://jsonplaceholder.typicode.com/users")
        .then(response => response.json())
        .then(resp => document.querySelector('.l2').innerHTML = resp[ram2].id)
    fetch("https://jsonplaceholder.typicode.com/photos")
        .then(response => response.json())
        .then(resp => document.querySelector('.img2').src = resp[Math.ceil(Math.random() * 5005)].url)
    fetch("https://jsonplaceholder.typicode.com/users")
        .then(response => response.json())
        .then(resp => document.querySelector('.p2').innerHTML = resp[ram2].address.suite[5] + resp[ram2].address.suite[6] + resp[ram2].address.suite[7])
    fetch("https://jsonplaceholder.typicode.com/posts")
        .then(response => response.json())
        .then(resp => document.querySelector('.te2').innerHTML = resp[Math.ceil(Math.random() * 100)].body)
    fetch("https://jsonplaceholder.typicode.com/users")
        .then(response => response.json())
        .then(resp => document.querySelector('.data2').href = resp[ram2].website)
    fetch("https://jsonplaceholder.typicode.com/users")
        .then(response => response.json())
        .then(resp => document.querySelector('.data2').innerHTML = resp[ram2].website)
}
fetch("https://jsonplaceholder.typicode.com/photos")
    .then(response => response.json())
    .then(resp => document.querySelector('.card__profile--img').src = resp[Math.ceil(Math.random() * 5005)].url)
fetch("https://jsonplaceholder.typicode.com/photos")
    .then(response => response.json())
    .then(resp => document.querySelector('.img2').src = resp[Math.ceil(Math.random() * 5005)].url)